config/routes.rb
Rails.application.routes.draw do

	root 'users#index'

  	devise_for :users
 	resources :users
 	resources :cities
 	resources :places
 	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

	has_many :users
end

app/models/place.rb
class Place < ApplicationRecord

	belongs_to :city
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_by_resource
  before_action :authenticate_user!

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    
	before_action :authenticate_user!
    
    layout 'application'
    
    def index
        @cities = City.all
    end

    def new
        @city = City.new
    end

    def create
        @city = City.new city_params

        if @city.save
            redirect_to city_path(@city)
        else            
            render 'new'
        end
    end

    def edit
        @city = City.find params[:id]
    end

    def show
        @city = City.find params[:id]
    end

    def update
        @city = City.find params[:id]
        if @city.update(city_params)           
            redirect_to city_path(@city)
        else            
            render 'edit'
        end
    end

    def destroy
        @city = City.find params[:id]
        @city.destroy
        redirect_to cities_path
    end
  
    private
    def city_params
        params.require(:city).permit!
    end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    
	before_action :authenticate_user!
    
    layout 'application'
    
    def index
        @places = Place.all
    end

    def new
        @place = Place.new
    end

    def create
        @place = Place.new place_params

        if @place.save
            redirect_to place_path(@place)
        else            
            render 'new'
        end
    end

    def edit
        @place = Place.find params[:id]
    end

    def show
        @place = Place.find params[:id]
    end

    def update
        @place = Place.find params[:id]
        if @place.update(place_params)           
            redirect_to place_path(@place)
        else            
            render 'edit'
        end
    end

    def destroy
        @place = Place.find params[:id]
        @place.destroy
        redirect_to places_path
    end
  
    private
    def place_params
        params.require(:place).permit!
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!

    layout 'application', :except => :view
    
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new user_params

        if @user.save
            redirect_to user_path(@user)
        else            
            render 'new'
        end
    end

    def edit
        @user = current_user
    end

    def show
        @user = User.find params[:id]
    end

    def update
        @user = User.find(current_user.id)
        if @user.update(user_params)           
            redirect_to user_path(@user)
        else            
            render 'edit'
        end
    end

    def destroy
        @user = User.find params[:id]
        @user.destroy
        redirect_to users_path
    end
  
    private
    def user_params
        params.require(:user).permit!
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	layout false

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/_form.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <%= form_for(@city) do |f| %>

                <table class="table">

                    <tr>
                        <td width="30%"><%= f.label :name, "Nombre" %></td>
                        <td><%= f.text_field :name ,class: 'form-control' %></td>
                    </tr>    
                   
                </table>

                <div class="row">
                    <div class="col-md-12 text-right">
                        <%= link_to "Atras", cities_path, class: 'btn btn-default' %>
                        <%= link_to "Cancelar", city_path(@city), class: 'btn btn-warning' if !@city.id.nil? %>
                        <button type="submit" class="btn btn-primary">Ingresar</button>
                    </div>
                </div>

                <% end -%>
            </div>
        </div>
    </div>
</div>

app/views/cities/edit.html.erb
<h1>Editar Ciudad</h1>

<%= render 'form' %>
<div style="clear: both;"></div>

app/views/cities/index.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Lista de Ciudades</h4>
                <div class="button-group pull right">
                    <%= link_to "crear ciudad", new_city_path, class: 'btn btn-success' %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
<!-- column -->
<div class="col-lg-12">
    <div class="card">
        <div class="card-block">
            
            <div class="table-responsive">
                <table class="table data-table">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>Nombre</th>
                            <th>Accion</th>
                        </tr>
                    </thead>
                    <tbody>                        
                        <% @cities.each do |city| %>
                        <tr>
                            <td><%= city.id %></td>
                            <td><%= city.name %></td>
                            <td><span><%= link_to "Detalle", city_path(city), class: 'btn btn-danger btn-xs' %></span> </td>
                        </tr>
                        <% end -%>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $('.data-table').dataTable().fnSort( [ [1,'asc'] ] );
    })
</script>

app/views/cities/new.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Crear Ciudad</h4>
            </div>
        </div>
    </div>
</div>
<%= render 'form' %>
<div style="clear: both;"></div>

app/views/cities/show.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Detalles de ciudad</h4>
                <div class="button-group pull right">
                    <%= link_to 'Regresar', cities_path, class: 'btn btn-default' %>
                    <%= link_to "Editar", edit_city_path(@city), class: 'btn btn-primary' %>            
                    <%= link_to "Borrar", city_path(@city), class: 'btn btn-danger', data: {method: 'DELETE', confirm: 'estas seguro?'} %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <table class="table">
                    <tr>
                        <td><b>Nombre:</b></td>
                        <td><%= @city.name %></td>
                    </tr>  
                </table>
            </div>
        </div>
    </div>
</div>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Soy ciudad</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>	
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <%= form_for(@place) do |f| %>

                <%= f.hidden_field :latitude %>
                <%= f.hidden_field :longitude %>

                <table class="table">

                    <tr>
                        <td width="30%"><%= f.label :acronym, "acronimo" %></td>
                        <td><%= f.text_field :acronym ,class: 'form-control' %></td>
                    </tr>    
                    <tr>
                        <td><%= f.label :name, "Nombre" %></td>
                        <td><%= f.text_field :name, class: 'form-control' %></td>
                    </tr>                    
                    <tr>
                        <td><%= f.label :city_id, "Ciudad*" %></td>
                        <td><%= f.select :city_id, options_for_select(City.all.map{|c| [c.name,c.id]}),{}, {:class => "form-control", :required => false} %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :phone, "telefono" %></td>
                        <td><%= f.text_field :phone, class: 'form-control' %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :address, "Direccion" %></td>
                        <td><%= f.text_field :address, class: 'form-control' %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :email, "Email" %></td>
                        <td><%= f.text_field :email, class: 'form-control' %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :email, "location" %></td>
                        <td><div id="map" style="width: 100%"></div></td>
                    </tr>
                    
                </table>

                <div class="row">
                    <div class="col-md-12 text-right">
                        <%= link_to "Atras", places_path, class: 'btn btn-default' %>
                        <%= link_to "Cancelar", place_path(@place), class: 'btn btn-warning' if !@place.id.nil? %>
                        <button type="submit" class="btn btn-primary">Ingresar</button>
                    </div>
                </div>

                <% end -%>
            </div>
        </div>
    </div>
</div>

<style>
#map {
    height: 300px;
}
</style>

<script>

var map;
var marker;

function initMap() {

    // setup map
    map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 4.355, lng: -74.045},
        zoom: 6
    });

    google.maps.event.addListener(map, 'click', function(event) {
       placeMarker(event.latLng);
    });

    // setup autocomplete

   autocomplete = new google.maps.places.Autocomplete(
        (document.getElementById('address')),
       {types: ['geocode']});

       // When the user selects an address from the dropdown, populate the address
       // fields in the form.
       autocomplete.addListener('place_changed', fillInAddress);
     

}

function geolocate() {
    if (navigator.geolocation) {
     navigator.geolocation.getCurrentPosition(function(position) {
       var geolocation = {
         lat: position.coords.latitude,
         lng: position.coords.longitude
       };
       var circle = new google.maps.Circle({
         center: geolocation,
         radius: position.coords.accuracy
       });
       autocomplete.setBounds(circle.getBounds());
     });
    }
}

function placeMarker(location) {

    if (marker == null)
    {
        marker = new google.maps.Marker({
            position: location,
            map: map
        });
    } else {
        marker.setPosition(location);
        console.log(location)
    }
    $("#place_latitude").val(eval(location.lat()));
    $("#place_longitude").val(eval(location.lng()));

}

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCF5SfRuKX2envJL-5cM4ruaOq1-KI0wbM&callback=initMap"
async defer></script>

app/views/places/edit.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Editar lugar</h4>
            </div>
        </div>
    </div>
</div>
<%= render 'form' %>
<div style="clear: both;"></div>

app/views/places/index.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Lista de lugares</h4>
                <div class="button-group pull right">
                    <%= link_to "crear lugar", new_place_path, class: 'btn btn-success' %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
<!-- column -->
<div class="col-lg-12">
    <div class="card">
        <div class="card-block">
            
            <div class="table-responsive">
                <table class="table data-table">
                    <thead>
                        <tr>
                            <th>Acronimo</th>
                            <th>Nombre</th>
                            <th>Ciudad</th>
                            <th>Direccion</th>
                            <th>Telefono</th>
                            <th>Latitud</th>
                            <th>Longitud</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>                        
                        <% @places.each do |place| %>
                        <tr>
                            <td><%= place.acronym %></td> 
                            <td><%= place.name %></td>
                            <td><%= place.city.name unless place.city.nil? %></td>
                            <td><%= place.address %></td>
                            <td><%= place.phone %></td>
                            <td><%= place.latitude %></td>
                            <td><%= place.longitude %></td>
                            <td><%= place.email %></td>
                            <td><span><%= link_to "Detalle", place_path(place), class: 'btn btn-danger btn-xs' %></span> </td>
                        </tr>
                        <% end -%>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $('.data-table').dataTable().fnSort( [ [1,'asc'] ] );
    })
</script>

app/views/places/new.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Crear lugar</h4>
            </div>
        </div>
    </div>
</div>
<%= render 'form' %>
<div style="clear: both;"></div>

app/views/places/show.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Detalles de lugar</h4>
                <div class="button-group pull right">
                    <%= link_to 'Regresar', places_path, class: 'btn btn-default' %>
                    <%= link_to "Editar", edit_place_path(@place), class: 'btn btn-primary' %>            
                    <%= link_to "Borrar", place_path(@place), class: 'btn btn-danger', data: {method: 'DELETE', confirm: 'estas seguro?'} %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <table class="table">
                    <tr>
                        <td><b>id:</b></td>
                        <td><%= @place.id %></td>
                    </tr>            
                    <tr>
                        <td><b>Acronimo:</b></td>
                        <td><%= @place.acronym %></td> 
                    </tr>
                    <tr>
                        <td><b>Nombre:</b></td>
                        <td><%= @place.name %></td> 
                    </tr>
                    <tr>
                        <td><b>Ciudad:</b></td>
                        <td><%= @place.city.name unless @place.city.nil? %></td>
                    </tr>
                    <tr>
                        <td><b>Direccion:</b></td>
                        <td><%= @place.address %></td>
                    </tr>
                    <tr>
                        <td><b>Telefono:</b></td>
                        <td><%= @place.phone %></td>
                    </tr>  
                    <tr>
                        <td><b>latitud:</b></td>
                        <td><%= @place.latitude %></td>
                    </tr>  
                    <tr>
                        <td><b>longitud:</b></td>
                        <td><%= @place.longitude %></td>
                    </tr>  
                    <tr>
                        <td><b>Email:</b></td>
                        <td><%= @place.email %></td>
                    </tr>    
               
                </table>
            </div>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <%= form_for(@user) do |f| %>

                <table class="table">

                    <tr>
                        <td width="30%"><%= f.label :first_name, "Nombre" %></td>
                        <td><%= f.text_field :first_name ,class: 'form-control' %></td>
                    </tr>    
                    <tr>
                        <td><%= f.label :last_name, "Apellido" %></td>
                        <td><%= f.text_field :last_name, class: 'form-control' %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :email, "Email" %></td>
                        <td><%= f.text_field :email, class: 'form-control' %></td>
                    </tr>
                    <tr>
                        <td width="30%"><%= f.label :password, "Contraseña" %></td>
                        <td><%= f.password_field :password, class: 'form-control' %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :password_confirmation, "Confirmacion de contraseña" %></td>
                        <td><%= f.password_field :password_confirmation, class: 'form-control' %></td>
                    </tr>
                    
                </table>

                <div class="row">
                    <div class="col-md-12 text-right">
                        <%= link_to "Atras", users_path, class: 'btn btn-default' %>
                        <%= link_to "Cancelar", user_path(@user), class: 'btn btn-warning' if !@user.id.nil? %>
                        <button type="submit" class="btn btn-primary">Ingresar</button>
                    </div>
                </div>

                <% end -%>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1>Editar usuario</h1>

<%= render 'form' %>
<div style="clear: both;"></div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Lista de Usuarios</h4>
                <div class="button-group pull right">
                    <%= link_to "crear usuario", new_user_path, class: 'btn btn-success' %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
<!-- column -->
<div class="col-lg-12">
    <div class="card">
        <div class="card-block">
            
            <div class="table-responsive">
                <table class="table data-table">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>                        
                        <% @users.each do |user| %>
                        <tr>
                            <td><%= user.id %></td>
                            <td><%= user.first_name %></td> 
                            <td><%= user.last_name %></td>                  
                            <td><%= user.email %></td>
                            <td><span><%= link_to "Detalle", user_path(user), class: 'btn btn-danger btn-xs' %></span> </td>
                        </tr>
                        <% end -%>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $('.data-table').dataTable().fnSort( [ [1,'asc'] ] );
    })
</script>

app/views/users/new.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Crear usuarios</h4>
            </div>
        </div>
    </div>
</div>
<%= render 'form' %>
<div style="clear: both;"></div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Detalles de usuario</h4>
                <div class="button-group pull right">
                    <%= link_to 'Regresar', users_path, class: 'btn btn-default' %>
                    <%= link_to "Editar", edit_user_path(@user), class: 'btn btn-primary' %>            
                    <%= link_to "Borrar", user_path(@user), class: 'btn btn-danger', data: {method: 'DELETE', confirm: 'estas seguro?'} %>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-xlg-6">
        <div class="card">
            <div class="card-block">
                <table class="table">
                    <tr>
                        <td><b>Nombre:</b></td>
                        <td><%= @user.first_name %></td>
                    </tr>            
                    <tr>
                        <td><b>Apellido:</b></td>
                        <td><%= @user.last_name %></td>
                    </tr>
                    <tr>
                        <td><b>Fecha de creacion:</b></td>
                        <td><%= @user.created_at %></td>
                    </tr>
                    <tr>
                        <td><b>Email:</b></td>
                        <td><%= @user.email %></td>
                    </tr>  
               
                </table>
            </div>
        </div>
    </div>
</div>